# Generated by Django 4.2.21 on 2025-05-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('edad', models.PositiveIntegerField()),
                ('fecha_ingreso', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono_casa', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_movil', models.CharField(max_length=20)),
                ('sueldo_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comision', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sueldo_bruto', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('password', models.CharField(max_length=128)),
                ('foto', models.ImageField(upload_to='empleados_fotos/')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
    ]
